### PR TITLE
Added ProjectType in projecttypes.json for Windows.Devices.GPIO and WinUI3

### PR DESCRIPTION
**Pull request by ghost**
@madskristensen; Updated the projecttypes.json to support projects I work on which include Windows.Devices.GPIO for WinUI3. Note: This will only show if the User's Project file contains:
```
	<ItemGroup>
		<ProjectCapability Include="Windows.Devices.Gpio" />
	</ItemGroup>
```

And it is a WinUI 3 Project that contains Windows.App.SDK.

This also validates what I stated in the Tutorial that Template developers can add project types to their template project file and update the HelpExplorer projecttypes.json to get it available to the user.

### CODE REVIEW

**Comment by ghost** [comment]
@madskristensen; Updated the projecttypes.json file for Android App/lib for .NET 6 built-in VS template. As usual the URL links may not be the ones the MS VS PM wants.

**Comment by ghost** [comment]
@madskristensen; Updated projecttypes.json to support DotNetCoreRazor built-in VS Templates.

**Comment by ghost** [comment]
@madskristensen; Updated projecttypes.json to support MS Teams App .NET Core

**Comment by ghost** [comment]
@madskristensen This seems to be the most I can do with built-in templates since many do not have any different capabilities between them. So, unless the Project Template older decides to add custom project capabilities to the template it would be hard to provide a more precise URL links.

**Comment by madskristensen** [comment]
Fantastic. Thank you so much

**Pull request merged**
