### PR TITLE
Added Option Page to allow display of display multiple projects

### PR DESCRIPTION
**Pull request by ghost**
Added Option Page.

Allows you to display multiple project types and links in the HelpExplorer Window or the first one found for your selected project.

### CODE REVIEW

**Comment by ghost** [comment]
The _WriteCapabilitiesToFile(value)_ only runs in debug mode and returns the following example files. This is easier than trying to get values out of the _string[] capabilities_ while running to add to values to the _projecttypes.json_ file.

[CSharp_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7576740/CSharp_Capabilities.txt)
[MauiBlazor_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7576741/MauiBlazor_Capabilities.txt)
[MauiCore_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7576742/MauiCore_Capabilities.txt)
[VSIX_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7576743/VSIX_Capabilities.txt)
[WindowsXAML_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7576744/WindowsXAML_Capabilities.txt)
[WPF_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7576745/WPF_Capabilities.txt)
[AspNetCore_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7576746/AspNetCore_Capabilities.txt)

**Comment by ghost** [comment]
Used some of the Capabilities found in the output files to update the _projecttypes.json_ file.

**Comment by madskristensen** [comment]
Awesome. Thank you!!!

**Comment by ghost** [comment]
Mads, if you can decide what Microsoft url's should be the ones used for each project and file types I will add them and test.  The ones I used may or may not be the best ones based on your PM's requirements.

**Comment by madskristensen** [comment]
Perhaps we can get @jasonchlus getting the right URLs for the content and add them to [this file](https://github.com/madskristensen/HelpExplorer/blob/master/src/Schema/projecttypes.json)?

**Comment by ghost** [comment]
Mads, I do need you to test something to be sure it is not my notebook. But in Visual Studio Enterprise 2022, when I go to the options page it does not load, if I cancel then open again it loads file, This seems to happen on more than HelpExplorer options on my machine.  If you see the same then I will open bug report.

**Comment by madskristensen** [comment]
I've never seen that happen before. Strange

**Comment by ghost** [comment]
So, does it happen on yours?

**Comment by ghost** [comment]
I meant to say Loads fine not (file)

**Comment by ghost** [comment]
I would send some screen shots but Syncfusion is updating on my system and I cannot run VS right now.

**Comment by ghost** [comment]
First loaded and even though it allows me to click HelpExplorer and General the results do not change.
First try

Then if I click away to and then back it stays the same as what the click away screen was. 
Second try

Then on the third click away and back it works and shows the correct options.  I also noticed in the first try if I cancel instead of clicking away the reopen the options from screech it displays correctly the first time.
worked try

**Comment by ghost** [comment]
I should mention that it does this in the exp instance of VS 2022, I have not tried with HelpExplorer installed to see if it is an issue with the debugger or the exp instance of VS 2022.

**Pull request merged**
