### PR TITLE
Updated WriteCapabilitiesToFile and General.cs

### PR DESCRIPTION
**Pull request by ghost**
Updated WriteCapabilitiesToFile to handle printing Non-Core and Core files. Found that if they had the same outcome name the last one created will not be right for researching project capabilities. This is a work in progress and once I figure out the official project types from each file it will be refined. As you can see from the attachments, they are vastly different.

[WPF_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7589835/WPF_CSharp_CPS_Capabilities.txt)
[WPF_CSharp_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7589837/WPF_CSharp_Capabilities.txt)

Also updated General.cs to only show the Enable print options if you are in debug mode. This will keep the release version from having an option that they cannot use.

### CODE REVIEW

**Comment by ghost** [comment]
Mads; submitted: https://developercommunity.visualstudio.com/t/tools-options-non-responsive/1593622
Since the Tools Option dialog is terribly slow and non-responsive even outside of exp instance.

**Comment by ghost** [comment]
Note: on the bug report for VS Tools Options, I see the same results using VS 2022 Enterprise Version 17.0.1 Preview

**Comment by ghost** [comment]
The Check fails with General.cs but the error mentioned is not correct since the file has the value in the updated file. Here is an example of the output files from this version.

[WPF_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7598476/WPF_CSharp_CPS_Capabilities.txt)
[AspNetCore_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7598478/AspNetCore_CSharp_CPS_Capabilities.txt)
[DotNetCoreWeb_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7598479/DotNetCoreWeb_CSharp_CPS_Capabilities.txt)
[CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7598480/CSharp_CPS_Capabilities.txt)

Have a happy Thanksgiving to you and your family Mads!

**Review by ghost — COMMENTED** [review]
Here are the test files created by the updated projecttypes.json file
[CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599627/CSharp_CPS_Capabilities.txt)
[NUnit_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599628/NUnit_CSharp_CPS_Capabilities.txt)
[Universal_Windows_Platform_CSharp_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599629/Universal_Windows_Platform_CSharp_Capabilities.txt)
[WindowsForms_ClassLibrary_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599630/WindowsForms_ClassLibrary_CSharp_CPS_Capabilities.txt)
[WindowsForms_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599631/WindowsForms_CSharp_CPS_Capabilities.txt)
[WinUI_App_Msix__CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599632/WinUI_App_Msix__CSharp_CPS_Capabilities.txt)
[WinUI_ClassLibrary_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599633/WinUI_ClassLibrary_CSharp_CPS_Capabilities.txt)
[WinUI_WapProj_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599634/WinUI_WapProj_CSharp_CPS_Capabilities.txt)
[WPF_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599635/WPF_CSharp_CPS_Capabilities.txt)
[WPFLibrary_CSharp_CPS_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7599636/WPFLibrary_CSharp_CPS_Capabilities.txt)
.

**Comment by madskristensen** [comment]
Let me know when this is ready to be merged

**Comment by ghost** [comment]
@madskristensen I updated my VSIXWPFAppWithDocFxLoggingAndZip.vsix marketplace template to support the providing custom Project Capabilities then updated the HelpExplorer projecttypes.json file to support those added Project Capabilities.

Based on my research you can add Project Capabilities very easy using the following in the templates project file.

```
	<ItemGroup>
		<ProjectCapability Include="DiagnoseCapabilities" />
		<ProjectCapability Include="Microsoft.Extensions.Logging" />
		<ProjectCapability Include="Docfx.Console" />
		<ProjectCapability Include="System.IO.Compression"/>
	</ItemGroup>
```

I then updated the projecttypes.json as follows to support those Custom Project Capabilities as follows.
```
    {
      "capability": "WPF & DocFx.Console & Microsoft.Extensions.Logging",
      "capabilityExpression": "(WPF & CSharp) & (CPS & CrossPlatformExecutable) & (DocFx.Console & Microsoft.Extensions.Logging)",
      "capabilitiesFileName": "WPF_CSharp_CPS_DocFx_Logging",
      "text": "You are working in an WPF Application project using DocFx and Microsoft.Extensions.Logging and might find these links useful.",
      "links": [
        {
          "text": "Getting started with WPF Application",
          "url": "https://docs.microsoft.com/en-us/dotnet/desktop/wpf/overview/?view=netdesktop-6.0"
        },
        {
          "text": "WPF tutorial",
          "url": "https://docs.microsoft.com/en-us/dotnet/desktop/wpf/get-started/create-app-visual-studio?view=netdesktop-6.0"
        },
        {
          "text": "DocFx tutorial",
          "url": "https://docs.microsoft.com/en-us/shows/on-net/intro-to-docfx"
        },
        {
          "text": "Microsoft.Extensions.Logging tutorial",
          "url": "https://docs.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line"
        }
      ]
    },
```
The results are as follows:
[WPF_CSharp_CPS_DocFx_Logging_Capabilities.txt](https://github.com/madskristensen/HelpExplorer/files/7670827/WPF_CSharp_CPS_DocFx_Logging_Capabilities.txt)

**Comment by ghost** [comment]
@madskristensen it is ready to be merged with the last addition I just added. Thanks. Please check it out and let me know what else I can do.

**Comment by madskristensen** [comment]
Thanks

**Comment by ghost** [comment]
@madskristensen You are very welcome, and I hope you had and will have incredibly happy holidays.
Would you want me to document the process and maybe update the README.MD file?

**Comment by madskristensen** [comment]
Happy holidays to you too!!

If you want to document it for others to learn from, that would be great

**Comment by Danny-McNaught** [comment]
Will do!

**Pull request merged**
